# Creating Data Frames Using Series

In [1]:
import numpy as np

In [2]:
import pandas as pd

Task 1: Create series with car price as value between 300000 & 500000 and index values from 101 to 120

In [3]:
np.random.seed(20)
cars=pd.Series(np.random.randint(30000,50001,20),index=np.arange(101,121,1))
cars

101    45715
102    34367
103    44729
104    33915
105    31607
106    49618
107    45328
108    38744
109    30474
110    41003
111    43267
112    31808
113    41005
114    33814
115    35264
116    34713
117    42773
118    37138
119    39222
120    39930
dtype: int32

Task 2 : Find total numbers of cars that have price greater than $400000

In [4]:
cars[cars>40000].size                                     #Total Number of cars that have a price greater than $40000

8

Task 3: Display records of all cars having model numbers from 111 to 116 and find highest price of car among them.

In [5]:
print('Records of all cars having model numbers from 111 to 116\n',cars.loc[111:116] ) #Displaying the record of all cars having model numbers from 111 to 116

print('Highest Price : ',max(cars.loc[111:116]))  #Highest Price of cars having model numbers from 111 to 116

Records of all cars having model numbers from 111 to 116
 111    43267
112    31808
113    41005
114    33814
115    35264
116    34713
dtype: int32
Highest Price :  43267


Task 4: Find records of all cars priced at between $30000 and $40000. Find the count.

In [6]:
cars[cars.between(30000,40000)]                      #Fetching records of cars priced at between $30000 and $40000

102    34367
104    33915
105    31607
108    38744
109    30474
112    31808
114    33814
115    35264
116    34713
118    37138
119    39222
120    39930
dtype: int32

In [7]:
cars[cars.between(30000,40000)].size                 #Count of cars priced at between $30000 and $ 40000

12

Task 5 : Find data of all cars with price greater than the average cars. Find count ofsuch cars.

In [9]:
print('Average price :',cars.mean())                     #Average Price of all cars

print(cars[cars>cars.mean()])                             #Data of all cars having price greater than average price

print('No of cars : ',cars[cars>cars.mean()].size)        #No of cars having price greater than average price

Average price : 38721.7
101    45715
103    44729
106    49618
107    45328
108    38744
110    41003
111    43267
113    41005
117    42773
119    39222
120    39930
dtype: int32
No of cars :  11


Task 6 : Add three new cars with model numbers 201,202 & 203 with price $34000,$45000 & $54000 respectively in existing records

In [10]:
new_id=[201,202,203]
new_price=[34000,45000,54000]
new_cars=pd.Series(new_price,index=new_id)
new_cars

201    34000
202    45000
203    54000
dtype: int64

In [11]:
cars=pd.concat([cars,new_cars])                            #Adding new records in existing records
cars

101    45715
102    34367
103    44729
104    33915
105    31607
106    49618
107    45328
108    38744
109    30474
110    41003
111    43267
112    31808
113    41005
114    33814
115    35264
116    34713
117    42773
118    37138
119    39222
120    39930
201    34000
202    45000
203    54000
dtype: int64

Task 7 : Offer 10% discount on cars priced at more than $40000. Display original and discounted price alongside

In [12]:
df1=pd.DataFrame(cars,columns=['Original_Price'])             #Converting series into dataframe df1


df2=0.9*df1[df1>40000]                                        #Creating dataframe df2 with discounted price on elligible cars
df2.update(df1[df1<=40000])
df2.columns=['Discounted_Price']

x=df1.join(df2)                                               #Merging two dataframes
x

Original_Price  Discounted_Price
101           45715           41143.5
102           34367           34367.0
103           44729           40256.1
104           33915           33915.0
105           31607           31607.0
106           49618           44656.2
107           45328           40795.2
108           38744           38744.0
109           30474           30474.0
110           41003           36902.7
111           43267           38940.3
112           31808           31808.0
113           41005           36904.5
114           33814           33814.0
115           35264           35264.0
116           34713           34713.0
117           42773           38495.7
118           37138           37138.0
119           39222           39222.0
120           39930           39930.0
201           34000           34000.0
202           45000           40500.0
203           54000           48600.0

In [13]:
#df2=pd.DataFrame(0.9*cars[cars>40000],columns=['Discounted Data'])

Task 8: Find number of cars with price between $ 30000 and $ 40000 before and after discount.

In [14]:
x[x.Original_Price.between(30000,40000)].shape[0]               #No of cars with price between $30000 and $40000 before discount

13

In [15]:
x[x.Discounted_Price.between(30000,40000)].shape[0]              #No of cars with price between $30000 and $40000 after discount

17

Task 9: Fetch records of five least expensive cars

In [18]:
x.Original_Price.sort_values(ascending=True)[0:5]                #Top 5 least expensive cars

109    30474
105    31607
112    31808
114    33814
104    33915
Name: Original_Price, dtype: int64